### ISSUE TITLE
No clear difference between theoretical and empirical correlogram

### ISSUE THREAD

**Issue by ErickChacon** [JuliaEarth/geospatial-data-science-with-julia#10]
In the following paragraph of the introduction of [chapter 10](https://juliaearth.github.io/geospatial-data-science-with-julia/10-correlation.html):

```
The sample Pearson correlation coefficient studied as a function of the lag $h$
is known as the **correlogram function**. For example, consider the exponential
correlogram function given by $cor(h) = \exp(-h)$:
```

The first sentence is defining the empirical **correlogram function**, but the example is providing a theoretical correlogram function. Maybe add a sentence before the example to present the theoretical correlogram? Or remove the word *sample* to refer to the theoretical correlogram?

**Comment by ErickChacon** [comment]
Similarly, in the same chapter, the empirical variogram is presented and described in terms of the following graph:

![image](https://github.com/JuliaEarth/geospatial-data-science-with-julia/assets/7862458/d0f4e81d-01c1-4fe5-b09b-02d2961eea58)

However, this graph is with respect to a theoretical variogram. For users without experience, this might be a bit confusing.

**Comment by juliohm** [comment]
Awesome feedback @ErickChacon. Fixing it.

**Comment by juliohm** [comment]
I've removed the "sample" reference as suggested. Regarding the plot, do you have suggestions to make the context more clear?

**Comment by ErickChacon** [comment]
At the begining of variography subsection, I would start presenting the definition of the theorerical variogram which is $1/2E[(Y_i-Y_j)]$, where $Y_i$ and $Y_j$ are random variables and not observed values. The following text and description would be respect to the theoretical variogram. Then, you can introduce the empirical variogram (maybe in 10.1.5) as an estimator of the theoretical variogram and clarify that it is is computed with respect to the observed values and provide the equation that is in terms of the sum of the squared difference of the observed values.

**Comment by juliohm** [comment]
I was thinking about it when I first wrote the chapter, and thought it
would be too theoretical for the target audience. I'll think about a small
adjustment to the text.

Em sex., 27 de out. de 2023 12:20, Dr. Erick A. Chacón Montalván <
***@***.***> escreveu:

**Comment by juliohm** [comment]
After reading the text again and again, I couldn't find a simple way to distinguish theoretical from empirical variograms without assuming a more advanced mathematical background from readers. The potential of confusion doesn't pay off, and so I will close the issue for now.

If you come up with a better phrasing or note, please feel free to submit suggestions. I think the text is clear enough as is for the intended audience.

Thanks for the awesome feedback as usual.
