### ISSUE TITLE
Prompt the reader to download the data files

### ISSUE THREAD

**Issue by daviewales** [JuliaEarth/geospatial-data-science-with-julia#6]
I may have missed it.
However, I got to this point without having downloaded the data files:

https://juliaearth.github.io/geospatial-data-science-with-julia/02-geoviz.html

I notice that they are here:
https://github.com/JuliaEarth/geospatial-data-science-with-julia/tree/main/data

But it would be good to prompted to download them to a suitable location at the start of the book, and perhaps reminded of this when they are used.

I see that you use GitHub Actions.
Perhaps you could add a step to zip the data directory and copy it to the quarto publish directory before publishing to GitHub pages. Then you could link it as:

https://juliaearth.github.io/geospatial-data-science-with-julia/data.zip

**Comment by juliohm** [comment]
Thank you @daviewales for the suggestion. We can add a section to the Preface explaining the data folder, and add notes pointing to it whenever the data is loaded in other chapters.
