### ISSUE TITLE
Intersection graph in chapter 04 does not seem right.

### ISSUE THREAD

**Issue by ErickChacon** [JuliaEarth/geospatial-data-science-with-julia#7]
In the section of [operations](https://juliaearth.github.io/geospatial-data-science-with-julia/04-geoproc.html#operations) there is an example of the intersection of 2 geometries. Is that graph right? 

```julia
outer = [(8, 0), (4, 8), (2, 8), (-2, 0), (0, 0), (1, 2), (5, 2), (6, 0)]
inner = [(4, 4), (2, 4), (3, 6)]
poly  = PolyArea([outer, inner])
quad  = Quadrangle((0, 1), (3, 1), (3, 7), (0, 7))

int = poly ∩ quad

viz([poly, quad, boundary(int)],
    color = ["slategray3", "teal", "red"],
    alpha = [1.0, 0.2, 1.0])
```

![image](https://github.com/JuliaEarth/geospatial-data-science-with-julia/assets/7862458/568c0a5e-70ca-4aa8-939b-543d224cf5f3)

I think there is a red segment in the center that should not be there?

**Comment by juliohm** [comment]
That is true. Probably an issue with the Sutherland-Hodgman clipping method: https://github.com/JuliaGeometry/Meshes.jl/blob/master/src/clipping/sutherlandhodgman.jl

The ultimate goal is to use a more general clipping method such as Weiler-Atherton: https://github.com/JuliaGeometry/Meshes.jl/blob/c470b18ab57256e0b902874b416296f535e6e696/src/intersections/polygons.jl#L6

We have an open issue for it: https://github.com/JuliaGeometry/Meshes.jl/issues/578

**Comment by juliohm** [comment]
We simplified the example in the meantime. Further work is needed in Meshes.jl to add these other algorithms.
